### ISSUE TITLE
可以出一个详细的使用教程吗

### ISSUE THREAD

**Issue by hujihan** [Error063/zjooc_fucker#10]
可以出一个详细的使用教程吗

**Comment by xuhe2** [comment]
README有docker运行方式, 也可以本地部署

**Comment by xuhe2** [comment]
克隆项目到本地, pip install -r requirements.txt 安装依赖, 使用python tui.py运行项目
- 你最好在终端使用命令行启动项目,而不是pycharm的终端启动

**Comment by hujihan** [comment]
感谢！我今天中午在pycharm终端启动了，UI一直乱跳，稍后我会尝试在cmd启动

**Comment by hujihan** [comment]
输入账号密码之后还是报错

```
PS C:\Users\**\Downloads\zjooc_fucker-master\fucker> python tui.py
Traceback (most recent call last):
  File "C:\Users\**\Downloads\zjooc_fucker-master\fucker\tui.py", line 51, in <module>
    code = code_file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 463: illegal multibyte sequence
```

**Comment by HoshinoStarry** [comment]
> 输入账号密码之后还是报错
> 
> 
> 
> ```
> 
> PS C:\Users\**\Downloads\zjooc_fucker-master\fucker> python tui.py
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\**\Downloads\zjooc_fucker-master\fucker\tui.py", line 51, in <module>
> 
>     code = code_file.read()
> 
> UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 463: illegal multibyte sequence
> 
> ```


文件编码问题，现在重新拉取代码看看

**Comment by hujihan** [comment]
可以了感谢！
